FROM node

RUN npm install -g autorest

ARG SWAGGER_CODEGEN_COMMIT
ARG GENERATION_XML_FILE
ARG SWAGGER_CODEGEN_USER_ORG

RUN apt-get update && apt-get -y install python-pip && pip install urllib3
RUN apt-get install libunwind8

COPY generate_client_in_container.csharp.sh /generate_client.sh
COPY preprocess_spec.py /
COPY custom_objects_spec.json /

ENTRYPOINT ["/generate_client.sh"]
