name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Install Python dependencies
        run: pip install 'urllib3>=2.0,<3.0'

      - name: Run unit tests
        working-directory: ./openapi
        run: python3 test_apidiscovery.py

      - name: Run integration tests
        working-directory: ./openapi
        run: bash test_integration.sh
